In [1]:
import numpy as np


In [2]:
mylist = [1, 2, 4, 5]
np.array(mylist)

array([1, 2, 4, 5])

In [3]:
mylist

[1, 2, 4, 5]

In [4]:
type(mylist)

list

In [5]:
arr = np.array(mylist)
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 4, 5])

In [7]:
a = np.arange(0, 10)


In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
type(1.0)

float

In [16]:
type(1.)

float

In [17]:
type(1)

int

In [18]:
np.random.randint(0,1999)

1125

In [19]:
np.random.randint(0,1999)

1548

In [20]:
np.random.randint(0,1999)

1704

In [21]:
np.random.randint(0,1999)


1570

In [22]:
np.random.randint(0,1999, (5,5))

array([[1859,    1,  719, 1554,  400],
       [ 511, 1127,  605, 1435, 1021],
       [ 308,  516,  895,  825,  978],
       [ 397,  220,  744, 1303,  582],
       [ 606, 1482, 1296,  711,  878]])

In [23]:
np.random.randint(0,1999, (33, 9))

array([[1959,  539,  905, 1259,  430, 1097,  145,  476,  982],
       [ 758,  943, 1283, 1460,   11,  542,  628, 1631,   95],
       [ 176, 1088, 1452,  686, 1631,  702, 1455,  233, 1635],
       [1627, 1852,  879, 1640,   44,  527, 1145, 1190, 1029],
       [1421,  964,   46,    5, 1487, 1851,  927,  307,  192],
       [1083,  107,  193,  654,  190, 1399, 1916, 1172,  154],
       [1829,  212,  777,  589,  274, 1034, 1940,  479,  956],
       [1227,   33,  114,  948,  552, 1971,  993, 1625, 1409],
       [  39, 1565, 1972,  448,  622, 1811, 1900,  881,  718],
       [ 947, 1682, 1240,  692, 1010, 1278, 1953, 1323, 1182],
       [1899,  343,  795, 1049, 1097,  250,   15,  775, 1910],
       [1705,  129, 1728,  265, 1718, 1841,   86, 1448, 1690],
       [1846, 1767, 1140, 1037, 1438, 1049, 1732, 1030,  936],
       [1953,  490,  227,  160,  273, 1206, 1437,  991,  221],
       [ 118, 1453, 1094,  641, 1312, 1826, 1767,  498,  424],
       [1899,  163,  525,  889,  845, 1707,  712,  561,

In [24]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [25]:
np.linspace(0,10,106)

array([ 0.        ,  0.0952381 ,  0.19047619,  0.28571429,  0.38095238,
        0.47619048,  0.57142857,  0.66666667,  0.76190476,  0.85714286,
        0.95238095,  1.04761905,  1.14285714,  1.23809524,  1.33333333,
        1.42857143,  1.52380952,  1.61904762,  1.71428571,  1.80952381,
        1.9047619 ,  2.        ,  2.0952381 ,  2.19047619,  2.28571429,
        2.38095238,  2.47619048,  2.57142857,  2.66666667,  2.76190476,
        2.85714286,  2.95238095,  3.04761905,  3.14285714,  3.23809524,
        3.33333333,  3.42857143,  3.52380952,  3.61904762,  3.71428571,
        3.80952381,  3.9047619 ,  4.        ,  4.0952381 ,  4.19047619,
        4.28571429,  4.38095238,  4.47619048,  4.57142857,  4.66666667,
        4.76190476,  4.85714286,  4.95238095,  5.04761905,  5.14285714,
        5.23809524,  5.33333333,  5.42857143,  5.52380952,  5.61904762,
        5.71428571,  5.80952381,  5.9047619 ,  6.        ,  6.0952381 ,
        6.19047619,  6.28571429,  6.38095238,  6.47619048,  6.57

In [26]:
np.random.seed(101)

In [27]:
np.random.randint(0,100,9)

array([95, 11, 81, 70, 63, 87, 75,  9, 77])

In [28]:
arr = np.random.randint(0, 100,10)

In [29]:
arr

array([40,  4, 63, 40, 60, 92, 64,  5, 12, 93])

In [30]:
arr.max()

93

In [31]:
arr.min()

4

In [32]:
arr.mean()

47.3

In [34]:
arr.argmax()

9

In [35]:
arr.argmin()

1

In [36]:
arr.reshape(2,5)

array([[40,  4, 63, 40, 60],
       [92, 64,  5, 12, 93]])

In [37]:
mat= np.arange(0,100).reshape(10,10)

In [38]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
mat[5,2]

52

In [40]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [42]:
mat[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
mat >50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [44]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	./
	../req.txt

nothing added to commit but untracked files present (use "git add" to track)


In [ ]:
!